name: Build Site

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - name: Build pdf, epub and site
        run: |
          echo 'export default { base: "/die-schlinge/" }' > docs/.vitepress/config.local.js
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ github.sha }}
          path: docs/.vitepress/dist
