name: Deploy Site

on:
  workflow_run:
    workflows: ["Build Site"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site-${{ github.event.workflow_run.head_sha }}
          path: site
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
